steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}', '.']
  dir: 'ezzy_traders_backend'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image=${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}'
  - '--port=8080'
  - '--region=${_REGION}'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--service-account=${_SERVICE_ACCOUNT}'
  - '--max-instances=2'
  - '--timeout=3600'
  - '--memory=512Mi'

images:
- ${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REPO_REGION: asia-southeast1-docker.pkg.dev
  _REPO_NAME: prod-app-repo
  _SERVICE_NAME: ezzi-traders-backend
  _REGION: asia-southeast1
  _PROJ_ID: ezzi-traders
  _SERVICE_ACCOUNT: sa-ezzi-traders-prod@ezzi-traders.iam.gserviceaccount.com


