"""add tax_percentage and discount_amount to quotation_item

Revision ID: 3151473b9ea3
Revises: 
Create Date: 2025-10-01 20:20:58.966018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3151473b9ea3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_item', sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('quotation_item', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_item', 'discount_amount')
    op.drop_column('quotation_item', 'tax_percentage')
    # ### end Alembic commands ###
